"""Tables declaration

Revision ID: c617fdb4e427
Revises: 
Create Date: 2026-04-18 17:51:40.104930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c617fdb4e427'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constellations',
    sa.Column('constellation_iau', sa.String(length=3), nullable=False),
    sa.Column('constallation_la_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('constellation_iau', name='constellation_pk')
    )
    op.create_table('stars',
    sa.Column('star_hip', sa.Integer(), nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('star_ra', sa.Float(), nullable=False),
    sa.Column('star_dec', sa.Float(), nullable=False),
    sa.Column('star_vmag', sa.Float(), nullable=False),
    sa.Column('star_bv_index', sa.Float(), nullable=True),
    sa.Column('star_constellation', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['star_constellation'], ['constellations.constellation_iau'], name='star_constellation_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('star_hip', name='star_pk')
    )
    op.create_table('starsedges',
    sa.Column('se_star_a', sa.Integer(), nullable=False),
    sa.Column('se_star_b', sa.Integer(), nullable=False),
    sa.CheckConstraint('se_star_a <> se_star_b', name='se_different_stars'),
    sa.ForeignKeyConstraint(['se_star_a'], ['stars.star_hip'], name='se_star_a_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['se_star_b'], ['stars.star_hip'], name='se_star_b_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('se_star_a', 'se_star_b', name='se_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starsedges')
    op.drop_table('stars')
    op.drop_table('constellations')
    # ### end Alembic commands ###
